const categoriesMenuData = {
  data: [
    {
      name: "Rice & Cereals",
      description: "Rice & Cereals",
      categories: [
        {
          _id: { $oid: "600de426e6ad373aac4f1599" },
          name: "Raw Rice",
          description: "Raw Rice",
          rootCategoryId: { $oid: "600ddecffc37ec23c85d7823" },
          createdAt: { $date: "2021-01-24T21:18:30.905Z" },
          updatedAt: { $date: "2021-01-24T21:23:48.443Z" },
          __v: 0,
          products: [
            {
              _id: { $oid: "601f992c4888396b00f8742c" },
              rating: 4.6,
              numReviews: 0,
              countInStock: 100,
              taxPercent: 5,
              name: "Vishudha Raw Rice",
              user: { $oid: "600a52657580f16694b10d91" },
              description: "Best Vishudha Raw Rice ",
              image: "/images/B-1-VISHNAVI-RICE",
              brand: "Vishudha",
              categoryId: { $oid: "600de426e6ad373aac4f1599" },
              isTaxable: true,
              reviews: [],
              availableInBulkPackages: [
                {
                  unitOfMessure: "25kg",
                  qty: 25,
                  unitPriceBulk: 1000,
                  sellingPriceUnit: 40,
                },
              ],
              availableInHouseholdPackages: [
                {
                  unitOfMessure: "1kg",
                  qty: 1,
                  unitPrice: 42,
                  sellingPriceUnit: 42,
                },
                {
                  unitOfMessure: "5kg",
                  qty: 5,
                  unitPrice: 210,
                  sellingPriceUnit: 42,
                },
                {
                  unitOfMessure: "10kg",
                  qty: 10,
                  unitPrice: 420,
                  sellingPriceUnit: 42,
                },
              ],
              createdAt: { $date: "2021-02-07T07:39:24.974Z" },
              updatedAt: { $date: "2021-02-07T07:39:24.974Z" },
              __v: 0,
            },
          ],
        },
        {
          _id: { $oid: "600df1bb24f4d639b8449054" },
          name: "Steamed Rice",
          description: "Steamed Rice",
          rootCategoryId: { $oid: "600ddecffc37ec23c85d7823" },
          createdAt: { $date: "2021-01-24T22:16:27.170Z" },
          updatedAt: { $date: "2021-01-24T22:16:27.170Z" },
          __v: 0,
          products: [
            {
              _id: { $oid: "601fa6faa5771666e458b314" },
              user: "600a52657580f16694b10d91",
              categoryId: "600df1bb24f4d639b8449054",
              name: "Pathang Rice",
              image: "/images/B-1-VISHNAVI-RICE",
              brand: "Pathang",
              description: "Pathang Rice",
              reviews: [],
              availableInBulkPackings: [
                {
                  unitOfMessure: "25kg",
                  qty: 25,
                  unitPrice: 45,
                  sellingPrice: 1125,
                },
              ],
              availableInHouseholdPackings: [
                {
                  unitOfMessure: "1kg",
                  qty: 1,
                  unitPrice: 47,
                  sellingPrice: 470,
                },
                {
                  unitOfMessure: "5kg",
                  qty: 5,
                  unitPrice: 47,
                  sellingPrice: 235,
                },
                {
                  unitOfMessure: "10kg",
                  qty: 10,
                  unitPrice: 47,
                  sellingPrice: 470,
                },
              ],
              rating: 4.6,
              numReviews: 12,
              countInStock: 100,
              isTaxable: true,
              taxPercent: 5,
            },
            {
              _id: { $oid: "601fa7caa5771666e458b315" },
              user: "600a52657580f16694b10d91",
              categoryId: "600df1bb24f4d639b8449054",
              name: "Blue HMT Rice",
              image: "/images/B-1-VISHNAVI-RICE",
              brand: "Blue ",
              description: "Blue HMT Rice",
              reviews: [],
              availableInBulkPackings: [
                {
                  unitOfMessure: "25kg",
                  qty: 25,
                  unitPrice: 38,
                  sellingPrice: 950,
                },
              ],
              availableInHouseholdPackings: [
                {
                  unitOfMessure: "1kg",
                  qty: 1,
                  unitPrice: 40,
                  sellingPrice: 40,
                },
                {
                  unitOfMessure: "5kg",
                  qty: 5,
                  unitPrice: 40,
                  sellingPrice: 200,
                },
                {
                  unitOfMessure: "10kg",
                  qty: 10,
                  unitPrice: 40,
                  sellingPrice: 400,
                },
              ],
              rating: 4.6,
              numReviews: 12,
              countInStock: 100,
              isTaxable: true,
              taxPercent: 5,
            },
            {
              _id: { $oid: "601fa905a5771666e458b316" },
              user: "600a52657580f16694b10d91",
              categoryId: "600df1bb24f4d639b8449054",
              name: "Cow Brand Rice",
              image: "/images/B-1-VISHNAVI-RICE",
              brand: "Cow brand",
              description: "Cow Brand Rice",
              reviews: [],
              availableInBulkPackings: [
                {
                  unitOfMessure: "25kg",
                  qty: 25,
                  unitPrice: 48,
                  sellingPrice: 1200,
                },
              ],
              availableInHouseholdPackings: [
                {
                  unitOfMessure: "1kg",
                  qty: 1,
                  unitPrice: 50,
                  sellingPrice: 50,
                },
                {
                  unitOfMessure: "5kg",
                  qty: 5,
                  unitPrice: 50,
                  sellingPrice: 250,
                },
                {
                  unitOfMessure: "10kg",
                  qty: 10,
                  unitPrice: 50,
                  sellingPrice: 500,
                },
              ],
              rating: 4.6,
              numReviews: 12,
              countInStock: 100,
              isTaxable: true,
              taxPercent: 5,
            },
            {
              _id: { $oid: "601faa5aa5771666e458b317" },
              user: "600a52657580f16694b10d91",
              categoryId: "600df1bb24f4d639b8449054",
              name: "Kurnool Sona Masoori Rice (Pink)",
              image: "/images/B-1-VISHNAVI-RICE",
              brand: "Kurnool Sona Masoori",
              description: "Kurnool Sona Masoori Rice (Pink)",
              reviews: [],
              availableInBulkPackings: [
                {
                  unitOfMessure: "25kg",
                  qty: 25,
                  unitPrice: 38,
                  sellingPrice: 950,
                },
              ],
              availableInHouseholdPackings: [
                {
                  unitOfMessure: "1kg",
                  qty: 1,
                  unitPrice: 40,
                  sellingPrice: 40,
                },
                {
                  unitOfMessure: "5kg",
                  qty: 5,
                  unitPrice: 40,
                  sellingPrice: 200,
                },
                {
                  unitOfMessure: "10kg",
                  qty: 10,
                  unitPrice: 50,
                  sellingPrice: 500,
                },
              ],
              rating: 4.6,
              numReviews: 12,
              countInStock: 100,
              isTaxable: true,
              taxPercent: 5,
            },
            {
              _id: { $oid: "601faadda5771666e458b318" },
              user: "600a52657580f16694b10d91",
              categoryId: "600df1bb24f4d639b8449054",
              name: "Purple HMT Rice",
              image: "/images/B-1-VISHNAVI-RICE",
              brand: "Purple HMT",
              description: "Purple HMT Rice",
              reviews: [],
              availableInBulkPackings: [
                {
                  unitOfMessure: "25kg",
                  qty: 25,
                  unitPrice: 41,
                  sellingPrice: 1025,
                },
              ],
              availableInHouseholdPackings: [
                {
                  unitOfMessure: "1kg",
                  qty: 1,
                  unitPrice: 43,
                  sellingPrice: 43,
                },
                {
                  unitOfMessure: "5kg",
                  qty: 5,
                  unitPrice: 43,
                  sellingPrice: 215,
                },
                {
                  unitOfMessure: "10kg",
                  qty: 10,
                  unitPrice: 43,
                  sellingPrice: 430,
                },
              ],
              rating: 4.6,
              numReviews: 12,
              countInStock: 100,
              isTaxable: true,
              taxPercent: 5,
            },
            {
              _id: { $oid: "601fab38a5771666e458b319" },
              user: "600a52657580f16694b10d91",
              categoryId: "600df1bb24f4d639b8449054",
              name: "Green HMT",
              image: "/images/B-1-VISHNAVI-RICE",
              brand: "Green HMT",
              description: "Green HMT",
              reviews: [],
              availableInBulkPackings: [
                {
                  unitOfMessure: "25kg",
                  "qty…escription": "Economy",
                  reviews: [],
                  availableInBulkPackings: {
                    unitOfMessure: "35kg",
                    qty: 35,
                    unitPrice: 37,
                    sellingPrice: 1295,
                  },
                  availableInHouseholdPackings: [
                    {
                      unitOfMessure: "1kg",
                      qty: 1,
                      unitPrice: 40,
                      sellingPrice: 40,
                    },
                    {
                      unitOfMessure: "5kg",
                      qty: 5,
                      unitPrice: 40,
                      sellingPrice: 200,
                    },
                    {
                      unitOfMessure: "10kg",
                      qty: 10,
                      unitPrice: 40,
                      sellingPrice: 400,
                    },
                  ],
                  rating: 4.6,
                  numReviews: 12,
                  countInStock: 100,
                  isTaxable: true,
                  taxPercent: 5,
                },
              ],
            },
            {
              _id: { $oid: "600df1f924f4d639b8449057" },
              name: "Murmura",
              description: "Murmura",
              rootCategoryId: { $oid: "600ddecffc37ec23c85d7823" },
              createdAt: { $date: "2021-01-24T22:17:29.404Z" },
              updatedAt: { $date: "2021-01-24T22:17:29.404Z" },
              __v: 0,
              products: [
                {
                  _id: { $oid: "601fc944a5771666e458b323" },
                  user: "600a52657580f16694b10d91",
                  categoryId: "600df1f924f4d639b8449057",
                  name: "Economy",
                  image: "/images/B-1-VISHNAVI-RICE",
                  brand: "Economy",
                  description: "Economy",
                  reviews: [],
                  availableInBulkPackings: {
                    unitOfMessure: "500gm pouch",
                    qty: 30,
                    unitPrice: 35,
                    sellingPrice: 1050,
                  },
                  availableInHouseholdPackings: [
                    {
                      unitOfMessure: "1kg",
                      qty: 1,
                      unitPrice: 38,
                      sellingPrice: 38,
                    },
                    {
                      unitOfMessure: "5kg",
                      qty: 5,
                      unitPrice: 38,
                      sellingPrice: 190,
                    },
                    {
                      unitOfMessure: "10kg",
                      qty: 10,
                      unitPrice: 38,
                      sellingPrice: 380,
                    },
                  ],
                  rating: 4.6,
                  numReviews: 12,
                  countInStock: 100,
                  isTaxable: true,
                  taxPercent: 5,
                },
                {
                  _id: { $oid: "601fca59a5771666e458b324" },
                  user: "600a52657580f16694b10d91",
                  categoryId: "600df1f924f4d639b8449057",
                  name: "Premium",
                  image: "/images/B-1-VISHNAVI-RICE",
                  brand: "Premium",
                  description: "Premium",
                  reviews: [],
                  availableInBulkPackings: {
                    unitOfMessure: "500gm pouch",
                    qty: 30,
                    unitPrice: 36,
                    sellingPrice: 1080,
                  },
                  availableInHouseholdPackings: [
                    {
                      unitOfMessure: "1kg",
                      qty: 1,
                      unitPrice: 39,
                      sellingPrice: 39,
                    },
                    {
                      unitOfMessure: "5kg",
                      qty: 5,
                      unitPrice: 39,
                      sellingPrice: 195,
                    },
                    {
                      unitOfMessure: "10kg",
                      qty: 10,
                      unitPrice: 38,
                      sellingPrice: 380,
                    },
                  ],
                  rating: 4.6,
                  numReviews: 12,
                  countInStock: 100,
                  isTaxable: true,
                  taxPercent: 5,
                },
              ],
            },
            {
              _id: { $oid: "600df21624f4d639b8449058" },
              name: "Idli Rice",
              description: "Idli Rice",
              rootCategoryId: { $oid: "600ddecffc37ec23c85d7823" },
              createdAt: { $date: "2021-01-24T22:17:58.610Z" },
              updatedAt: { $date: "2021-01-24T22:17:58.610Z" },
              __v: 0,
              products: [
                {
                  _id: { $oid: "601fcb0aa5771666e458b325" },
                  user: "600a52657580f16694b10d91",
                  categoryId: "600df21624f4d639b8449058",
                  name: "Premium",
                  image: "/images/B-1-VISHNAVI-RICE",
                  brand: "Premium",
                  description: "Premium",
                  reviews: [],
                  availableInBulkPackings: {
                    unitOfMessure: "25kg",
                    qty: 25,
                    unitPrice: 39,
                    sellingPrice: 975,
                  },
                  availableInHouseholdPackings: [
                    {
                      unitOfMessure: "1kg",
                      qty: 1,
                      unitPrice: 42,
                      sellingPrice: 42,
                    },
                    {
                      unitOfMessure: "5kg",
                      qty: 5,
                      unitPrice: 42,
                      sellingPrice: 210,
                    },
                    {
                      unitOfMessure: "10kg",
                      qty: 10,
                      unitPrice: 41,
                      sellingPrice: 410,
                    },
                  ],
                  rating: 4.6,
                  numReviews: 12,
                  countInStock: 100,
                  isTaxable: true,
                  taxPercent: 5,
                },
                {
                  _id: { $oid: "601fcb8ba5771666e458b326" },
                  user: "600a52657580f16694b10d91",
                  categoryId: "600df21624f4d639b8449058",
                  name: "Premium",
                  image: "/images/B-1-VISHNAVI-RICE",
                  brand: "Premium",
                  description: "Premium",
                  reviews: [],
                  availableInBulkPackings: {
                    unitOfMessure: "25kg",
                    qty: 25,
                    unitPrice: 36,
                    sellingPrice: 900,
                  },
                  availableInHouseholdPackings: [
                    {
                      unitOfMessure: "1kg",
                      qty: 1,
                      unitPrice: 39,
                      sellingPrice: 39,
                    },
                    {
                      unitOfMessure: "5kg",
                      qty: 5,
                      unitPrice: 39,
                      sellingPrice: 195,
                    },
                    {
                      unitOfMessure: "10kg",
                      qty: 10,
                      unitPrice: 39,
                      sellingPrice: 390,
                    },
                  ],
                  rating: 4.6,
                  numReviews: 12,
                  countInStock: 100,
                  isTaxable: true,
                  taxPercent: 5,
                },
              ],
            },
          ],
        },
        {
          name: "Edible Oils",
          description: "Edible Oils",
          categories: [
            {
              _id: { $oid: "601fea5da5771666e458b328" },
              name: "Palm Oil",
              description: "Palm Oil",
              rootCategoryId: { $oid: "600ddef7fc37ec23c85d7824" },
              products: [],
            },
            {
              _id: { $oid: "601fead0a5771666e458b329" },
              name: "Sunflower Oil",
              description: "Sunflower Oil",
              rootCategoryId: { $oid: "600ddef7fc37ec23c85d7824" },
              products: [],
            },
            {
              _id: { $oid: "601feaefa5771666e458b32a" },
              name: "Groundnut Oil",
              description: "Groundnut Oil",
              rootCategoryId: { $oid: "600ddef7fc37ec23c85d7824" },
              products: [],
            },
            {
              _id: { $oid: "601feb11a5771666e458b32b" },
              name: "Mustard Oil",
              description: "Mustard Oil",
              rootCategoryId: { $oid: "600ddef7fc37ec23c85d7824" },
              products: [],
            },
            {
              _id: { $oid: "601feb46a5771666e458b32c" },
              name: "Gingelli Oil",
              description: "Gingelli Oil",
              rootCategoryId: { $oid: "600ddef7fc37ec23c85d7824" },
              products: [],
            },
            {
              _id: { $oid: "601feb60a5771666e458b32d" },
              name: "Ghee",
              description: "Ghee",
              rootCategoryId: { $oid: "600ddef7fc37ec23c85d7824" },
              products: [],
            },
            {
              _id: { $oid: "601feb7ba5771666e458b32e" },
              name: "Vanaspathi",
              description: "Vanaspathi",
              rootCategoryId: { $oid: "600ddef7fc37ec23c85d7824" },
              products: [],
            },
            {
              _id: { $oid: "601febaaa5771666e458b32f" },
              name: "Rice Bran",
              description: "Rice Bran",
              rootCategoryId: { $oid: "600ddef7fc37ec23c85d7824" },
              products: [],
            },
            {
              _id: { $oid: "601febdca5771666e458b330" },
              name: "Coconut Oil",
              description: "Coconut Oil",
              rootCategoryId: { $oid: "600ddef7fc37ec23c85d7824" },
              products: [],
            },
          ],
        },
      ],
    },
  ],
};
export default categoriesMenuData;
